### PR TITLE
compatibility with fava 1.23.1

### PR DESCRIPTION
**Pull request by vascosantos**
In response to https://github.com/kubauk/fava-review/issues/10#issuecomment-1412006036

### CODE REVIEW

**Comment by kubauk** [comment]
Hi, thanks for the submission.

Could you please also update the tests?

You can validate that this working by running `poetry run pytest test`.

Also please update the fava version in pyproject.toml to the new minimal requirement of 1.23.1.

**Comment by vascosantos** [comment]
Hi, it seems it's working now.

**Comment by kubauk** [comment]
Looks like there is an incompatibility with the version of poetry that the actions select. I've made it too strict and the version of poetry is not accepting your lock as the version is outdated compared to your lock. This needs to be fixed here https://github.com/kubauk/fava-review/blob/99d518d3f1138fd11114a591884c8110d527fbc1/.github/workflows/fava-review.yml#L30.

**Comment by kubauk** [comment]
Thanks for the contribution. This PR closes issue 10

**Pull request merged**
